version: 2
jobs:
  build:
    docker:
      - image: python:3.8-alpine
      
    working_directory: ~/repo
    steps:
      - checkout
      
      - restore_cache:
             keys: 
               - v1-dependencies-{{ checksum "requirements.txt" }}
               - v1-dependencies-
               
      - run:
          name: install python
          command: |
             python3 -m venv venv
             . venv/bin/activate
      - run:
          name: install dependencies
          command: |       
             make install
             
      - run:
          name: install hadolint
          command: |             
             wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.10.0/hadolint-Linux-x86_64 
                 chmod +x /bin/hadolint
                 
      - save_cache:
           paths:
             - ./venv
           key: v1-dependencies-{{ checksum "requirements.txt" }}
            
      - run:
         name: run lint
         command: |
           . venv/bin/activate
           make lint